Trip CRUD
Pago-TW/pago-backend pull request #5
Opened 2022-12-17 08:33 UTC by ycday

@Shiun0413 麻煩你確認一下

2022-12-18 00:07 UTC, Shiun0413 commented on pago-backend/src/main/java/tw/pago/pagobackend/entity/Trip.java
> +    private Integer trip_id;
@ycday 
Java 宣告變數應使用駝峰式命名

2022-12-18 00:17 UTC, Shiun0413 commented on pago-backend/src/main/java/tw/pago/pagobackend/dao/impl/TripDAOImpl.java
> +        String sql = "SELECT * FROM trip WHERE trip_id = ?";
@ycday 
應將要查詢的欄位打出來，避免使用 * 取得所有資料，原因是並非所有資料都必須查詢出來，有些資料是給程式判斷用的，多餘的資料被查詢會造成效能浪費

2022-12-18 00:56 UTC, Shiun0413 requested changes

2022-12-18 00:56 UTC, Shiun0413 commented on pago-backend/src/main/java/tw/pago/pagobackend/dao/impl/TripDAOImpl.java
> +    public Trip get(Integer trip_id) throws SQLException {
@ycday 
資料庫查詢方法的命名請使用getBy{查詢條件}, findBy{查詢條件}, queryBy{查詢條件}
get, find, query的詳細差異，可以參考[find vs. get - Thomas Uhrig](https://tuhrig.de/find-vs-get/)
原因有以下
1. 雖然我們是用JDBC的資料庫操作方式，但在JPA裡面的方法都是使用這種方式命名，甚至是React也是，在多種應用上都有使用此邏輯來命名
2. 可以透過方法名就直接知道這個查詢是放了什麼篩選條件
3. 若日後某功能的查詢方法有兩個以上，就會需要引入命名規範來保持程式可讀性

2022-12-18 01:04 UTC, Shiun0413 requested changes

2022-12-18 01:04 UTC, Shiun0413 commented on pago-backend/src/main/java/tw/pago/pagobackend/entity/Trip.java
> +    private String arrival_date;
@ycday 
Java 宣告變數應使用駝峰式命名

2022-12-18 03:23 UTC, ycday commented on pago-backend/src/main/java/tw/pago/pagobackend/dao/impl/TripDAOImpl.java
> +        String sql = "SELECT * FROM trip WHERE trip_id = ?";
@Shiun0413 已修改

2022-12-18 03:23 UTC, ycday commented on pago-backend/src/main/java/tw/pago/pagobackend/dao/impl/TripDAOImpl.java
> +    public Trip get(Integer trip_id) throws SQLException {
@Shiun0413 已修改

2022-12-18 03:23 UTC, ycday commented on pago-backend/src/main/java/tw/pago/pagobackend/entity/Trip.java
> +    private String arrival_date;
@Shiun0413 已修改

2023-01-02 20:31 UTC, Shiun0413 approved these changes

2023-01-02 20:31 UTC, merged